---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elasticsearch_role
  - src: git@github.com:vovinet/kibana-role.git
    scm: git
    version: "1.0.0"
    name: kibana_role
  - src: git@github.com:vovinet/filebeat-role.git
    scm: git
    version: "1.0.0"
    name: filebeat_role
